### PR TITLE
Brave: Update to Version 1.20.110-71

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Velgus** [comment]
I ran the auto PR - everything should be updated. Been kind of sleeping on this repo, sorry.

**Comment by ghost** [comment]
No problem. I wanted more experience opening pull requests because I haven't done many. Sorry for the Discord one I didn't see this until now

**Comment by Velgus** [comment]
No worries. 

Just for note, most scoop repos that use the official bucket, or Ash258's generic bucket as templates have a system for automatically updating all manifests using scoop's functionality. All you have to do is run `./bin/auto-pr -p` on your fork, and it will update all the manifests assuming the manifest has been set up correctly and there hasn't been some change on the website providing the downloads.

If you did this as a branch in your fork, you could also just PR all the changes at once in case I haven't updated it in a while.

**Comment by ghost** [comment]
That's awesome thank you! I knew there was a way to autoupdate so thanks for telling me how. I moved my own scoop bucket over to Ash258's template and I got autoupdate working but AppVeyor  won't let me do anything on their site without giving me an error and telling me to contact support. Oh well. I don't really need that anyway.

**Pull request closed without merging**
